Repository piyoki/nixos-config, pull requests merged in 2024-03, with the labels that each got.

#65 feat(theme/gtk): add tokyonight-theme
  themes/gtk/default.nix
Labels: feature

#66 feat(system): add greetd to launch Hyprland
  home/services/default.nix
  home/services/wayland-session/default.nix
  home/services/wayland-session/hyprland.nix
  system/services/default.nix
  system/services/displaymanager.nix
  system/services/greetd.nix
  themes/gtk/default.nix
Labels: feature

#67 patch(system): do nix-gc every day; remove links older than 3d
  profiles/thinkpad-x1-carbon/configuration.nix
Labels: patch

#68 feat(system/font): add dogica font
  flake.lock
  system/services/default.nix
  themes/fonts/custom-fonts.nix
Labels: feature

#69 patch(system/greetd): use tuigreet
  system/services/default.nix
  system/services/greetd.nix
Labels: patch

#70 refactor: rework {system,home}/package module
  home/packages/default.nix
  home/packages/networking/default.nix
  home/packages/windowmanager/hyprland/media/default.nix
  home/packages/windowmanager/hyprland/productivity/default.nix
  home/packages/windowmanager/hyprland/system/default.nix
  home/packages/windowmanager/hyprland/terminal/default.nix
  system/default.nix
  system/environment/default.nix
  system/networking/default.nix
  system/packages/bpf.nix
  system/packages/core.nix
  system/packages/default.nix
  system/packages/misc.nix
  system/packages/nixos.nix
  system/packages/trace.nix
Labels: refactor

#71 refactor(flake): multi-system prep
  flake.nix
  profiles/thinkpad-x1-carbon/configuration.nix
  profiles/thinkpad-x1-carbon/hardware-configuration.nix
  system/default.nix
  system/internationalisation/default.nix
  system/internationalisation/i18n.nix
  system/internationalisation/time.nix
Labels: refactor, optimize

#72 refactor(flake): use universal module definition
  flake.nix
  system/default.nix
Labels: refactor, optimize

#73 feat(flake): introduce genSystem to dynamically integrate modules
  flake.nix
Labels: refactor, optimize

#74 ci: integrate justfile to speed up tasks
  justfile
  system/packages/core.nix
Labels: feature

#76 patch(system): only enable greetd for laptop host
  flake.lock
  profiles/thinkpad-x1-carbon/modules/default.nix
  system/services/default.nix
Labels: feature

#77 refactor(home): modularize app configs (hypr,waybar)
  flake.lock
  flake.nix
  home/apps/hypr/default.nix
  home/apps/waybar/default.nix
  justfile
  profiles/nuc-12/home.nix
  profiles/nuc-12/modules/dotfiles.nix
  system/default.nix
Labels: refactor

#78 optimize/refactor(home): modularize app config
  home/apps/dunst/default.nix
  home/apps/fish/default.nix
  home/apps/hypr/default.nix
  home/apps/kitty/default.nix
  home/apps/lazygit/default.nix
  home/apps/lf/default.nix
  home/apps/nvim/default.nix
  home/apps/qutebrowser/default.nix
  home/apps/rofi/default.nix
  home/apps/swappy/default.nix
  home/apps/swaylock/default.nix
  home/apps/tmux/default.nix
  home/apps/waybar/default.nix
  home/common/default.nix
  home/common/options.nix
  home/default.nix
Labels: refactor, optimize

#79 patch(home): apply tiny patches
  home/common/options.nix
  home/default.nix
  home/vars.nix
Labels: patch

#80 optimize(home/common): add genOption func
  home/common/options.nix
Labels: optimize

#81 optimize(flake): refine genSystem func
  flake.nix
Labels: optimize

#83 optimize/refactor(flake): refine homeModules integration
  docs/bootstrap-system.md
  flake.nix
  profiles/nuc-12/home.nix
  profiles/nuc-12/modules/gnupg.nix
  profiles/thinkpad-x1-carbon/home.nix
  profiles/thinkpad-x1-carbon/modules/dotfiles.nix
  profiles/thinkpad-x1-carbon/modules/gnupg.nix
Labels: refactor, optimize

#84 feat/refactor(profiles): add shared module, rework profiles module
  home/common/default.nix
  home/default.nix
  profiles/nuc-12/configuration.nix
  profiles/nuc-12/home.nix
  profiles/nuc-12/modules/default.nix
  profiles/thinkpad-x1-carbon/configuration.nix
  profiles/thinkpad-x1-carbon/home.nix
  profiles/thinkpad-x1-carbon/modules/default.nix
  shared/home.nix
  shared/modules/home/gnupg.nix
  shared/modules/system/powermanagement.nix
  shared/options.nix
  shared/vars/home.nix
Labels: refactor, feature

#85 refactor(profiles): import gnupg shared module
  profiles/nuc-12/home.nix
  profiles/nuc-12/modules/gnupg.nix
  profiles/thinkpad-x1-carbon/home.nix
  profiles/thinkpad-x1-carbon/modules/gnupg.nix
  shared/modules/home/gnupg.nix
Labels: refactor

#87 refactor: relocate vars module to shared/vars/default.nix
  docs/bootstrap-system.md
  flake.lock
  flake.nix
  shared/home.nix
  shared/vars/default.nix
  shared/vars/home.nix
  system/internationalisation/i18n.nix
  system/internationalisation/time.nix
Labels: refactor

#88 refactor(system): migrate nixos configs to shared/nixos.nix module
  shared/nixos.nix
  system/default.nix
Labels: refactor

#91 refactor/optimize: better modularization
  profiles/mars/configuration.nix
  profiles/nuc-12/home.nix
  profiles/nuc-12/modules/secrets.nix
  profiles/nuc-12/secrets/default.nix
  profiles/thinkpad-x1-carbon/home.nix
  profiles/thinkpad-x1-carbon/modules/secrets.nix
  profiles/thinkpad-x1-carbon/secrets/default.nix
  shared/server/home/base.nix
  shared/server/home/packages.nix
  shared/server/system/base.nix
  system/networking/default.nix
  system/networking/networkmanager.nix
  system/networking/server.nix
  system/services/gnupg/agent.nix
  system/services/gnupg/default.nix
  system/services/gnupg/server.nix
  system/services/openssh/default.nix
  system/services/openssh/server.nix
  system/users/server.nix
Labels: refactor, optimize

#92 refactor: rework gnupg-related modules
  home/services/encryption/default.nix
  home/services/encryption/server.nix
  home/services/encryption/sops.nix
  shared/modules/home/gnupg.nix
  shared/modules/home/scdaemon.conf
  shared/server/conf/gnupg.conf
  shared/server/home/base.nix
  shared/server/home/packages.nix
  system/services/gnupg/base.nix
  system/services/gnupg/default.nix
  system/services/gnupg/server.nix
  system/services/gnupg/yubikey.nix
  system/services/openssh/default.nix
Labels: refactor

#93 patch(flake): use nixpkgs-unstable-small
  flake.lock
  flake.nix
  system/services/openssh/default.nix
Labels: patch

#95 feat(profiles): enable boot.tmp.cleanOnBoot
  flake.lock
  profiles/mars/hardware-configuration.nix
  profiles/nuc-12/hardware-configuration.nix
  profiles/thinkpad-x1-carbon/hardware-configuration.nix
Labels: feature

#96 optimize(flake): better inputs modularization control
  flake.nix
  shared/modules/system/tmpfs/persistent/base.nix
  shared/nixos.nix
  system/networking/sdwan.nix
Labels: optimize

#97 chore: demise legacy persistent module import
  profiles/mars/configuration.nix
  profiles/mars/persistent.nix
  shared/modules/system/tmpfs/persistent/base.nix
  system/users/server.nix
Labels: chore

#98 ci(justfile): add count recipe
  justfile
Labels: ci

#100 patch(profiles): apply boot tweaks
  profiles/mars/configuration.nix
  profiles/mars/hardware-configuration.nix
  profiles/nuc-12/hardware-configuration.nix
  profiles/thinkpad-x1-carbon/hardware-configuration.nix
Labels: patch

#102 feat(shared): add dedicated secrets module
  flake.lock
  flake.nix
  home/default.nix
  home/secrets/default.nix
  home/secrets/minio.nix
  home/secrets/rclone.nix
  home/secrets/ssh.nix
  home/services/encryption/server.nix
  profiles/nuc-12/configuration.nix
  profiles/nuc-12/home.nix
  profiles/server/felix/configuration.nix
  profiles/server/mars/configuration.nix
  profiles/server/mars/home.nix
  profiles/thinkpad-x1-carbon/configuration.nix
  profiles/thinkpad-x1-carbon/home.nix
  shared/modules/secrets/default.nix
  shared/server/age-key.nix
  shared/server/system/base.nix
  shared/server/system/secrets.nix
  system/default.nix
  system/secrets/age-keys.nix
  system/secrets/default.nix
  system/secrets/init-pass.nix
  system/secrets/samba.nix
  system/secrets/sdwan.nix
Labels: refactor, feature

#103 patch(home/assets): fetch wallpapers from assets input
  flake.lock
  flake.nix
  home/assets/wallpaper.nix
Labels: patch

#104 refactor/optimize: leverage mergeAttrsList for better profile import
  flake.lock
  flake.nix
  justfile
Labels: refactor, optimize

#105 chore/style(pre-commit): add local shell hooks
  .pre-commit-config.yaml
  flake.nix
  home/services/encryption/server.nix
  justfile
  profiles/server/felix/hardware-configuration.nix
  shared/modules/secrets/default.nix
Labels: chore, style

#106 refactor(profiles): nuc-12,x1-carbon -> profiles/daily-drivers/
  flake.nix
  profiles/daily-drivers/nuc-12/conf/gpg.conf
  profiles/daily-drivers/nuc-12/configuration.nix
  profiles/daily-drivers/nuc-12/hardware-configuration.nix
  profiles/daily-drivers/nuc-12/home.nix
  profiles/daily-drivers/nuc-12/secrets/default.nix
  profiles/daily-drivers/nuc-12/secrets/gitconfig.nix
  profiles/daily-drivers/thinkpad-x1-carbon/conf/gpg.conf
  profiles/daily-drivers/thinkpad-x1-carbon/configuration.nix
  profiles/daily-drivers/thinkpad-x1-carbon/hardware-configuration.nix
  profiles/daily-drivers/thinkpad-x1-carbon/home.nix
  profiles/daily-drivers/thinkpad-x1-carbon/modules/dotfiles.nix
  profiles/daily-drivers/thinkpad-x1-carbon/secrets/default.nix
  profiles/daily-drivers/thinkpad-x1-carbon/secrets/gitconfig.nix
Labels: refactor

#107 patch(hardware-configuration): use latest rc kernel (6.8rc6)
  profiles/daily-drivers/nuc-12/hardware-configuration.nix
  profiles/daily-drivers/thinkpad-x1-carbon/hardware-configuration.nix
Labels: patch

#108 patch(profiles/hardware-configuration): fetch latestKernel (6.8rc7) from pkgs-unstable
  flake.lock
  flake.nix
  profiles/daily-drivers/nuc-12/hardware-configuration.nix
  profiles/daily-drivers/thinkpad-x1-carbon/hardware-configuration.nix
Labels: patch

#109 ci(justfile): enable load-dotenv; set default profile from env
  .gitignore
  flake.nix
  justfile
Labels: feature, ci

#111 ci(cron-sync-upstream): sync multiple inputs at once
  .github/workflows/cron-sync-hyprland-upstream.yml
  .github/workflows/cron-sync-upstream.yml
Labels: ci

#112 feat(flake): add neovim-nightly-overlay
  flake.lock
  flake.nix
  shared/home.nix
  shared/server/home/packages.nix
Labels: feature

#114 ci(cron-sync-upstream): add generate-access-token step
  .github/workflows/cron-sync-upstream.yml
Labels: ci

#115 refactor(flake): separate profiles from flake
  flake.nix
  profiles.nix
Labels: refactor

#116 ci(justfile): add new recipes
  justfile
Labels: ci

#118 refactor: demise nodejs,markdownlint settings
  .markdownlint-cli2.jsonc
  package.json
  yarn.lock
Labels: refactor

#119 feat(shared): add persistent.nix tailored to daily-driver profiles
  flake.lock
  flake.nix
  profiles/daily-drivers/nuc-12/configuration.nix
  profiles/daily-drivers/nuc-12/hardware-configuration.nix
  shared/daily-driver/persistent.nix
  shared/modules/system/tmpfs/persistent/dirs/common-xdg-dirs.nix
  system/users/default.nix
  system/users/server.nix
Labels: refactor, feature

#120 refactor(profile): rename daily-driver -> workstation
  flake.nix
  profiles.nix
  profiles/workstations/nuc-12/conf/gpg.conf
  profiles/workstations/nuc-12/configuration.nix
  profiles/workstations/nuc-12/hardware-configuration.nix
  profiles/workstations/nuc-12/home.nix
  profiles/workstations/nuc-12/secrets/default.nix
  profiles/workstations/nuc-12/secrets/gitconfig.nix
  profiles/workstations/thinkpad-x1-carbon/conf/gpg.conf
  profiles/workstations/thinkpad-x1-carbon/configuration.nix
  profiles/workstations/thinkpad-x1-carbon/hardware-configuration.nix
  profiles/workstations/thinkpad-x1-carbon/home.nix
  profiles/workstations/thinkpad-x1-carbon/modules/dotfiles.nix
  profiles/workstations/thinkpad-x1-carbon/secrets/default.nix
  profiles/workstations/thinkpad-x1-carbon/secrets/gitconfig.nix
  shared/modules/secrets/default.nix
  shared/workstation/persistent.nix
Labels: refactor

#121 feat(shared/modules): add dedicated persistent module
  profiles/server/mars/configuration.nix
  profiles/workstation/nuc-12/configuration.nix
  shared/modules/secrets/default.nix
  shared/modules/system/tmpfs/persistent/base.nix
  shared/modules/system/tmpfs/persistent/default.nix
  shared/modules/system/tmpfs/persistent/dirs/common-home-dirs.nix
  shared/modules/system/tmpfs/persistent/dirs/common-misc-dirs.nix
  shared/modules/system/tmpfs/persistent/dirs/common-system-dirs.nix
  shared/modules/system/tmpfs/persistent/dirs/common-xdg-dirs.nix
  shared/modules/system/tmpfs/persistent/dirs/extra-xdg-dirs.nix
  shared/modules/system/tmpfs/persistent/files/workstation-home-specific.nix
  shared/modules/system/tmpfs/persistent/files/workstation-system-specific.nix
  shared/modules/system/tmpfs/persistent/server.nix
  shared/workstation/persistent.nix
Labels: refactor, feature

#122 feat(shared): add sharedLib attr
  flake.nix
  profiles/workstation/nuc-12/configuration.nix
  shared/lib/default.nix
  shared/modules/system/tmpfs/persistent/default.nix
Labels: feature

#123 refactor(profiles): adopt relativeToRoot path
  profiles/server/felix/configuration.nix
  profiles/server/felix/home.nix
  profiles/server/mars/configuration.nix
  profiles/server/mars/home.nix
  profiles/workstation/nuc-12/configuration.nix
  profiles/workstation/nuc-12/home.nix
  profiles/workstation/thinkpad-x1-carbon/configuration.nix
  profiles/workstation/thinkpad-x1-carbon/home.nix
Labels: refactor

#125 refactor:(home,system): adopt scanPath imports
  home/apps.nix
  home/apps/default.nix
  home/default.nix
  shared/lib/default.nix
  system/default.nix
Labels: refactor

#126 feat(flake): add genCheck func
  flake.nix
Labels: refactor

#131 feat(profile/sdwan): enable swappiness
  profiles/server/sdwan-gateway/modules/sysctl.nix
Labels: feature

#132 feat(profile/sdwan): enable tcp_fastopen
  profiles/server/sdwan-gateway/modules/sysctl.nix
Labels: feature

#133 feat(profile/sdwan): apply throughput tweaks
  profiles/server/sdwan-gateway/modules/sysctl.nix
Labels: feature

#134 optimize(profile/sdwan): apply tcp_conn optimization
  profiles/server/sdwan-gateway/modules/sysctl.nix
Labels: optimize

#136 refactor(profile/sdwan): decouple configs into modules
  profiles/server/sdwan-gateway/configuration.nix
  profiles/server/sdwan-gateway/modules/networking.nix
  profiles/server/sdwan-gateway/modules/packages.nix
  profiles/server/sdwan-gateway/modules/services.nix
  profiles/server/sdwan-gateway/modules/users.nix
Labels: refactor

#137 refactor(profiles/server): simplify base modules import
  profiles/server/felix/configuration.nix
  profiles/server/mars/configuration.nix
  profiles/server/sdwan-gateway/configuration.nix
  profiles/server/sdwan-gateway/modules/packages.nix
  profiles/server/sdwan-gateway/modules/services.nix
  shared/server/system/base.nix
  shared/server/system/environment/default.nix
  shared/server/system/environment/vim.nix
  shared/server/system/patches/users-shell-bash.nix
  shared/server/system/services/default.nix
  shared/server/system/services/qemu-agent.nix
  shared/server/system/services/sops.nix
  system/packages/core.nix
  system/packages/server.nix
Labels: refactor

#139 feat(system/networking): add udp-gro-forwarding module
  profiles/server/sdwan-gateway/modules/services.nix
  profiles/server/tailscale-gateway/modules/services.nix
  system/networking/udp-gro-forwarding.nix
  system/packages/server.nix
  system/services/powermanagement/laptop.nix
Labels: feature

#140 patch(shared/options): demise options module
  home/apps/dunst/default.nix
  home/apps/fish/default.nix
  home/apps/hypr/default.nix
  home/apps/kitty/default.nix
  home/apps/lazygit/default.nix
  home/apps/lf/default.nix
  home/apps/nvim/default.nix
  home/apps/qutebrowser/default.nix
  home/apps/rofi/default.nix
  home/apps/swappy/default.nix
  home/apps/swaylock/default.nix
  home/apps/tmux/default.nix
  home/apps/waybar/default.nix
  home/default.nix
  profiles/server/sdwan-gateway/home.nix
  profiles/server/tailscale-gateway/home.nix
  shared/options.nix
  shared/server/home/base.nix
  system/networking/udp-gro-forwarding.nix
Labels: patch

#142 feat(flake): add microvm support
  .gitignore
  flake.lock
  flake.nix
  justfile
  profiles.nix
  shared/modules/microvm/firecracker.nix
Labels: feature

#143 patch(shared/server/patches): apply tcp_keepalive tweaks
  flake.nix
  shared/server/system/patches/sysctl-networking-tweaks.nix
Labels: patch

#144 refactor(flake): rework profiles args
  flake.nix
  profiles.nix
  profiles/server/felix/home.nix
  profiles/server/sdwan-gateway/home.nix
  profiles/server/tailscale-gateway/home.nix
Labels: refactor

#145 optimize(flake): inherit specialArgs
  flake.nix
Labels: optimize

#146 feat(shared/modules): add dedicated docker-compose-systemd module
  profiles/server/felix/configuration.nix
  profiles/server/felix/modules/networking.nix
  profiles/server/mars/configuration.nix
  profiles/server/mars/modules/networking.nix
  shared/modules/containerisation/docker-compose.nix
Labels: feature

#148 feat(home/app): add atuin client config
  home/apps/atuin/config.toml
  home/apps/atuin/default.nix
Labels: feature

#149 feat(home/service): add atuin-client module
  flake.lock
  home/apps/atuin/config.toml
  home/apps/atuin/default.nix
  home/packages/windowmanager/hyprland/terminal/default.nix
  home/services/atuin-client/config.toml
  home/services/atuin-client/default.nix
  home/services/default.nix
Labels: feature

#150 refactor(home/{pkgs,maintenace,libs}): adopt scanPath
  home/libs/default.nix
  home/maintenance/default.nix
  home/packages/default.nix
  home/packages/windowmanager/default.nix
  home/packages/windowmanager/hyprland/default.nix
Labels: refactor

#151 feat(shared/modules/secrets): add atuin secrets
  flake.nix
  profiles.nix
  shared/modules/secrets/default.nix
  shared/server/age-key.nix
  shared/server/secrets/age-key.nix
  shared/server/secrets/atuin-server.nix
Labels: feature

#152 fix/refactor(shared/modules/secrets): fix internal conflicts
  profiles/workstation/nuc-12/configuration.nix
  profiles/workstation/nuc-12/home-secrets/default.nix
  profiles/workstation/nuc-12/home-secrets/gitconfig.nix
  profiles/workstation/nuc-12/home.nix
  profiles/workstation/thinkpad-x1-carbon/configuration.nix
  profiles/workstation/thinkpad-x1-carbon/home-secrets/default.nix
  profiles/workstation/thinkpad-x1-carbon/home-secrets/gitconfig.nix
  profiles/workstation/thinkpad-x1-carbon/home.nix
  shared/modules/secrets/default.nix
  shared/modules/system/tmpfs/persistent/files/workstation-system-specific.nix
  shared/server/secrets/atuin-server.nix
Labels: refactor, fix

#153 patch(system): apply some general tweaks
  profiles/workstation/nuc-12/hardware-configuration.nix
  profiles/workstation/nuc-12/home.nix
  profiles/workstation/thinkpad-x1-carbon/hardware-configuration.nix
  profiles/workstation/thinkpad-x1-carbon/home.nix
  shared/nixos.nix
  shared/server/secrets/age-key.nix
  shared/server/secrets/atuin-server.nix
  system/packages/misc.nix
Labels: patch

#154 feat(flake): add inputs.chaotic; upgrade to cachyos kernel
  README.md
  flake.lock
  flake.nix
  home/packages/windowmanager/hyprland/browser/default.nix
  home/packages/windowmanager/hyprland/editor/default.nix
  home/packages/windowmanager/hyprland/im/default.nix
  home/packages/windowmanager/hyprland/media/default.nix
  profiles/workstation/nuc-12/hardware-configuration.nix
  profiles/workstation/thinkpad-x1-carbon/hardware-configuration.nix
  shared/home.nix
  shared/nixos.nix
Labels: feature

#155 sched_ext schedulers and tools
  system/services/atuin/default.nix
  system/services/default.nix
  system/services/scx.nix
Labels: feature

#156 ci(justfile): refine syntax, add annotations
  justfile
Labels: ci

#157 feat(system/pkgs): add mesa,intel related pkgs
  flake.lock
  flake.nix
  profiles/server/felix/hardware-configuration.nix
  profiles/server/mars/hardware-configuration.nix
  profiles/server/sdwan-gateway/hardware-configuration.nix
  profiles/server/tailscale-gateway/hardware-configuration.nix
  profiles/workstation/nuc-12/hardware-configuration.nix
  profiles/workstation/thinkpad-x1-carbon/hardware-configuration.nix
  shared/modules/microvm/firecracker.nix
  system/packages/misc.nix
  system/security/default.nix
Labels: feature

#158 feat(profiles/workstation): enable mesa-git
  flake.lock
  flake.nix
  home/packages/windowmanager/hyprland/editor/default.nix
  home/packages/windowmanager/hyprland/productivity/default.nix
  profiles.nix
  profiles/workstation/nuc-12/hardware-configuration.nix
  profiles/workstation/thinkpad-x1-carbon/hardware-configuration.nix
  shared/nixos.nix
  shared/overlays/default.nix
  system/packages/misc.nix
Labels: feature

#159 feat(home/app): persist alacritty configs
  flake.lock
  home/apps/alacritty/default.nix
  shared/modules/system/tmpfs/persistent/default.nix
  shared/modules/system/tmpfs/persistent/files/common-home-files.nix
Labels: feature

#160 refactor(home/app): rework app modules
  flake.lock
  flake.nix
  home/apps/alacritty/default.nix
  home/apps/dunst/default.nix
  home/apps/fish/default.nix
  home/apps/hypr/default.nix
  home/apps/kitty/default.nix
  home/apps/lazygit/default.nix
  home/apps/lf/default.nix
  home/apps/nvim/default.nix
  home/apps/qutebrowser/default.nix
  home/apps/rofi/default.nix
  home/apps/swappy/default.nix
  home/apps/swaylock/default.nix
  home/apps/tmux/default.nix
  home/apps/waybar/default.nix
Labels: refactor

#161 optimize(profiles/server): use cachyos kernel and enable scx
  README.md
  profiles/server/felix/hardware-configuration.nix
  profiles/server/mars/hardware-configuration.nix
  profiles/server/sdwan-gateway/configuration.nix
  profiles/server/sdwan-gateway/hardware-configuration.nix
  profiles/server/tailscale-gateway/configuration.nix
  profiles/server/tailscale-gateway/hardware-configuration.nix
  profiles/workstation/nuc-12/hardware-configuration.nix
  profiles/workstation/thinkpad-x1-carbon/hardware-configuration.nix
Labels: optimize

#162 optimize(profiles): use lto-kernel for better performance
  profiles/server/felix/hardware-configuration.nix
  profiles/server/mars/hardware-configuration.nix
  profiles/server/sdwan-gateway/hardware-configuration.nix
  profiles/server/tailscale-gateway/hardware-configuration.nix
  profiles/workstation/nuc-12/hardware-configuration.nix
  profiles/workstation/thinkpad-x1-carbon/hardware-configuration.nix
Labels: feature

#164 feat(flake): add chaotic-kernel upstream; pin to a specific sha
  flake.lock
  flake.nix
  profiles/server/felix/hardware-configuration.nix
  profiles/server/mars/hardware-configuration.nix
  profiles/server/sdwan-gateway/hardware-configuration.nix
  profiles/server/tailscale-gateway/hardware-configuration.nix
  profiles/workstation/nuc-12/hardware-configuration.nix
  profiles/workstation/thinkpad-x1-carbon/hardware-configuration.nix
Labels: feature

#165 refactor(system/services): use dedicated windowmanager module
  system/services/default.nix
  system/services/windowmanager/default.nix
  system/services/windowmanager/hyprland.nix
Labels: feature

#166 refactor({system,home}/service) demise systemd module
  docs/systemd-timer-usage.md
  docs/systemd-usage.md
  home/services/rclone/default.nix
  home/services/scdaemon/default.nix
  home/services/swayidle/default.nix
  home/services/systemd/cron/default.nix
  home/services/systemd/default.nix
  home/services/systemd/hooks/default.nix
  home/services/systemd/powermanagement/default.nix
  home/services/systemd/rclone.nix
  system/services/default.nix
  system/services/rclone.nix
Labels: refactor

#167 feat(home/pkgs): add foot
  flake.lock
  home/apps/foot/default.nix
  home/apps/kitty/default.nix
  home/packages/windowmanager/hyprland/productivity/default.nix
Labels: feature

#168 patch(shared/server/sysctl): apply sysctl tweaks
  shared/server/system/patches/sysctl-networking-tweaks.nix
Labels: patch

#169 patch(shared/server/sysctl): apply additional sysctl tweaks
  shared/server/system/patches/sysctl-networking-tweaks.nix
Labels: patch

#170 chore(flake): update inputs
  flake.lock
  flake.nix
Labels: chore

#171 feat(flake): integrate nix-fast-build
  .gitignore
  README.md
  flake.nix
  justfile
Labels: feature

#172 feat(home/pkgs): add vesktop
  home/packages/windowmanager/hyprland/im/default.nix
Labels: feature

#173 feat(shared/overlays): add webcord overlays
  docs/overlays-usage.md
  home/packages/windowmanager/hyprland/im/default.nix
  shared/overlays/default.nix
  shared/overlays/webcord.nix
Labels: feature

#174 feat(shared/overlays): add qutebrowser overlays
  shared/overlays/default.nix
  shared/overlays/qutebrowser.nix
Labels: feature

#176 chore(flake): add inputs.pilots
  README.md
  flake.lock
  flake.nix
Labels: chore

#178 feat(home/pkgs): adopt qutebrowser_nightly
  flake.lock
  home/apps/qutebrowser/default.nix
  home/packages/windowmanager/hyprland/browser/default.nix
  shared/overlays/default.nix
  shared/overlays/qutebrowser.nix
Labels: feature

#180 feat(shared/nixos): enable binary cache for nixospilots
  shared/nixos.nix
Labels: feature

#181 ci: add monitor-upstream-release workflow
  .github/workflows/monitor-upstream-release.yml
Labels: ci

#182 feat(home/pkgs/browser): add chromium
  home/packages/windowmanager/hyprland/browser/chromium.nix
  home/packages/windowmanager/hyprland/browser/default.nix
  home/packages/windowmanager/hyprland/browser/qutebrowser.nix
  themes/gtk/default.nix
Labels: feature

#183 feat(home/app): persist fcitx5 settings
  home/apps/fcitx5/conf/chttrans.conf
  home/apps/fcitx5/conf/classicui.conf
  home/apps/fcitx5/conf/cloudpinyin.conf
  home/apps/fcitx5/conf/pinyin.conf
  home/apps/fcitx5/default.nix
  home/apps/fcitx5/profile
Labels: feature

#185 patch(home/apps/fcitx5): persist all fcitx5-related configs
  home/apps/fcitx5/conf/cached_layouts
  home/apps/fcitx5/conf/classicui.conf
  home/apps/fcitx5/conf/cloudpinyin.conf
  home/apps/fcitx5/conf/notifications.conf
  home/apps/fcitx5/conf/punctuation.conf
  home/apps/fcitx5/config
  home/apps/fcitx5/default.nix
  home/packages/development/default.nix
Labels: patch

#186 chore(flake): update all upstream inputs
  flake.lock
  flake.nix
Labels: chore

#188 refactor(system): rework users module
  profiles/server/mars/configuration.nix
  system/users/basic.nix
  system/users/default.nix
  system/users/fish.nix
  system/users/server.nix
Labels: refactor
